### ISSUE TITLE
Good News, increase 4196 chunk size helps

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#117]
Good News, increase 4196 chunk size (HD cluster, sector size) might help against "peer disconnects"
(Or just waiting a day or two, video server guys get alarms??)

Didnt make much sense for video streams since internet packets are steady stream of 1540 bytes, altgh understandable for html, text files.

Did first 8x4196,  no "peer disconnect" for 12 hours, only one "stuck" case./
Now 8x8x4019 ehich might help against fragmentation on HD too (havnt yet moved NTFS volume to Windows too see what it looks like)

Gunnar

PS A bad guess, paclets dont always arrive "in order" over many server. gateway etc links.
Might mess up ACKs, etc when socket buffers emptied too often.

Latency, latency, says 5G too.

**Comment by aajanki** [comment]
I assume that you are referring to [this](https://github.com/aajanki/yle-dl/blob/master/yledl/downloaders.py#L123) parameter in the `urlretrieve` function in the `downloaders.py`. I increased it slightly.

It doesn't actually refer to the size of network data frames or video data frames. It's just a number of bytes to copy from a kernel buffer to an application buffer.

Also, Python code doesn't need to care about missing packets or packets arriving in a wrong order, because those are already taken care of on the TCP level by the kernel.
