### ISSUE TITLE
Consider downloading live streams as HLS

### ISSUE THREAD

**Issue by aajanki** [aajanki/yle-dl#124]
The live streams in Areena web player are played back as HLS streams while yle-dl downloads the HDS version. What would be the pros and cons of switching yle-dl over to HLS?

**Comment by gunnar12** [comment]
What would be the pros and cons of switching yle-dl over to HLS?/

I still do live streams in DOS batch file + adobehds, except Femma in ffmpeg-windows which gets stuck now and then randomly (need to close TCP connection and it continues)

- In theory one could resume even a live stream if HLS or adobehds, if one keeps track of last OK-segment number or even all old segments on harddisk..
Howver, standard adobeds doesnt do tha for live streams,only archived (wthout little own code)
Ffmpeg , AFAIK, cant be made to resume or handle segments as segments?

Sometimes needed if one or something ends or stalls recording too early.

Gunnar

PS Also another HLS-ffmpeg-mplayer (windows?) problem for live streams,
Mplayer doesnt want to play (mp4) live-file after 51 min 40s , tries to index-on-fly?  which has some bug.
One can fool it beyond that but then same problem again at twice that time.
Need to wait an guesstimate end of movie, because after ffmpeg stopped it "finalizes indexes" and no 51m problem anymore,
