### ISSUE TITLE
pip ?install wish and problem

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#130]
Any chance one cld easily have different versions installed so that they can be command-run (linux)

yle-dl,  pick latest version
yle-dl2.3, yle-dl2.9,etc, the specific versions, or something like that.

Havnt walked thrgh the whole install process, but got stuck some time ago.
Installed v2.9 again and again but yle-dl command still started v2.3.

Turned out there was a something path file (not on a linux machine  now) with paths to packages under python2.7
The list in that file still had the old 2.3 higher up,  before the 2.9 was added lower down. 
Deleted 2.3 entry and 2.9 started.
Check during install of them-them pip-eggs??

"You have many versions installed, do you want to give them separate yle-dl-n.m names?" please answer YES!

Gunnar

**Comment by aajanki** [comment]
I haven't tried this but it should be possible with Python virtualenvs. More info here: http://docs.python-guide.org/en/latest/dev/virtualenvs/

Notice that very old versions do not work because there has been changes in Areena. Anything older than 2.23 is unlikely to work because Areena moved to HTTPS addresses.

Installing the previous version, for example, would go roughly like this:
```
virtualenv yle-dl-2.26
source yle-dl-2.26/bin/activate
sudo pip install yle-dl=2.26
```
