### ISSUE TITLE
avoid two simultaneous downloads of same file

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#134]
Check for already open for write (but not read, as a videoplayer)?
Allow reading but block writing, like sometimes in databasesl
Rtmpdump does this by "failing" on opening file.

Use that buddy-file to signal "busy downloading"?

Needed when using lists, wld also make updating, additions to list possible on-the-run.

PS seems Linux is happy having two writing a file at the same time as it is done now,
Was-is same for rtmpdump. Used to abort the one who had downloaded more, trusting the johnny-came-later wld do the rest of the file correctly (neither one are at least using append)

PPS video-player might behave weird if file grows while playing, but their problem.

**Comment by aajanki** [comment]
This would need to be implemented in the extenal programs that do the downloading (wget, ffmpeg, AdobeHDS.php, rtmpdump, youtube-dl) because they open the output file for writing. It seems none of the programs support file locking. Because the cost of simultaneous downloads is just some wasted download bandwidth, I'm not going to do anything related to this.
