### ISSUE TITLE
resume but skip checking adobeHDS-flv file

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#136]
Havnt walked thrgh code, but guess it takes time if starting checking timestamps from beginning.
Rtmpdump does a quick check from end of the file for last timestamp, which obv causes othr problems

Anyway, wld be nice to have a "resume but skip checking adobeHDS-flv files"

I tried giving yle-dl " ", or nothing as backends but is said invalid and quit.
If I gave nothing as adobeHDS path it went to try youtubedl.

Giving just one backend as adobehdsphp did it? somehing "permission denied" and continues, but cld be easier 

PS That is, Im running --resume on old download-lists.

Would also need a "resume only already started files" or actually "check(length) and fix" to avoid redownloading fil;es that I have moved somewhere else.
(need them multiple --chkdir1,2,3,4 for that to work seamlessly)

**Comment by aajanki** [comment]
Yes, the resume checking is slow when using the adobehds backend because it essentially plays the video from the beginning to the end using ffmpeg.

I don't want to implement the resume-but-skip-adobehds functionality because then you could just not use resume at all, but there might be faster ways to check is a file is completely downloaded. Some ideas (mainly notes to myself): Maybe it is enought to consider a file complete if there are no AdobeHDS.php segments files present? How does youtoube-dl check for completed files?

**Comment by aajanki** [comment]
The resume is now fast also on AdobeHDS streams. yle-dl now avoids playing the video from start to finish. It assumes that if a file exists and that no fragment files are present, then the stream has been fully downloaded.
