### ISSUE TITLE
If expired, move file?? resume and srt file date

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#137]
I move them just to a sub-directory OLD, same partition, happens in split second.
Every now and then I move the content of that directory to another HD, which takes transfer time.

One more, when using --resume yle-dl first downloads, wites srt files, then checks if resume needed.
Result is, as now when I re-run old lists, new (overwritten) versions of srt files, with new date.

Wld it be possible to 
- first not write srt files
- check if video file needs resuming
- only then, if needed, redownload srt files again and write them.

Wld keep them and the video file at least close together when using modified as sort.
Hmm. seems the create-time also changes in Linux? didnt do it in Windows??

PS  Any chance that the new srt files of expired programs are kindo different or even empty??
(Luckily it doesnt look like that. A fancy solution wld obvs first compare them, do something smart if different?? hehe)

PPS Hmm?? what about other meta data?? havnt looked at that. (although happy abt that possibility. program jpg start-picture too?)

PPPS Despite my OKOKOK detection from RD-SUCCESS in v. 2.23? many video files need a resume despite RD-SUCCESS (at some level). 
Mostly 2-4GByte files, more chance for things to go wrong or some systematic (server) thing?
Had noticed some such cases alrdy month ago. Now resume seems to work 200% proof?
(like the usa shuttle)

PPS v 2.23?? and v 2/27 use different functions to download, but both deep down urlib2,3?
Both also no-protocol pure byte-stream? (not like ffmpeg) 
Shld be compatible in terms of present resume from-byte system?? no??

**Comment by aajanki** [comment]
The code now checks if the subtitle file exists and skips re-downloading it if it does. Hopefully the contents of a subtitle file never changes because the updated subtitles would not get downloaded (unless the user deletes the subtitle file).

Checking first if resume is needed and only then deciding whether or not to download subtitles would be a nicer solution but impossible, because the resume check is in most cases done by an external downloader process (AdobeHDS, wget, etc.) and it's not possible to hook the subtitle downloading to them.

**Comment by gunnar12** [comment]
because the resume check is in most cases done by an external downloader //

Butbutbut, its YLE-DL who tells them to try to resume
(I know, a little more complicated than that, adobeHDS "autoresumes" if filename changed, using old fragments if same but not deleted, wget?? havnt checked in details)
