### ISSUE TITLE
Incorrect error when missing ffmpeg

### ISSUE THREAD

**Issue by richrd** [aajanki/yle-dl#146]
I was a bit confused when trying to use yle-dl on my new machine. It was complaining about geo restrictions but the actual cause was missing ffmpeg (it does say that too, but the final error is misleading).
Here's last three lines of output:
```
ERROR: No such file or directory: b'ffmpeg'
WARNING: Failed! Possible reason: geo restriction.
WARNING: This video is available only in Finland.
```

**Comment by aajanki** [comment]
I hid the geo restriction warning when the download fails because of a missing executable and in other cases when the failure reason is not related to the geo restriction.

The geo restriction warning is shown when yle-dl can't figure out what went wrong, so it might still appear inappropriately in some cases.
