### ISSUE TITLE
"WARNING: Resume not supported on this stream" on all streams

### ISSUE THREAD

**Issue by probus** [aajanki/yle-dl#183]
Resume flag has stopped working for me after updating yle-dl today. Every title produces the same warning "WARNING: Resume not supported on this stream". This used to work on the same shows/files before.

**Comment by aajanki** [comment]
The latest yle-dl uses ffmpeg by default because only ffmpeg supports the new Areena subtitle format. However, ffmpeg does not support resuming as you have noticed.

There are no perfect options at the moment. Your alternatives are:
* The latest yle-dl: subtitles but no resume
* The latest yle-dl with `--backend wget`: resume but no subtitles
* Downgrade to yle-dl 20181221 resume but unreliable subtitle support

In the long run, I may drop the resume support completely unless I can figure out a way to make it work on ffmpeg.

**Comment by Jormangeud** [comment]
ffmpeg supports sending headers with '-headers'. That should enable resuming with range header and then combining the files.

**Comment by aajanki** [comment]
Great idea! I hadn't thought of that. I'll need to experiment to see if it is possible to get working resume with that.

**Comment by probus** [comment]
Great! In case that doesn't work out, I only use resume flag to prevent yle-dl from downloading duplicates.

**Comment by gunnar12** [comment]
prevent yle-dl from downloading duplicates/.

I do an UGLY patch in extractprs.py to prevent "alternative name"
I add EXISTS to the filename(after .mp4 extention) and ffmpeg cant handle it.
Unluckily wget doesnt mind it, just downloads it.

Havnt had time, but need to find some higher-up code where I can check for this ugly EXIST at end od of filename string and properly skip downloading.
Its a pain all these mini-modules called here and there from everywhere 

    def next_available_filename(self, proposed):
        i = 1
        enc = sys.getfilesystemencoding()
        filename = proposed
        basename, ext = os.path.splitext(filename)
        while os.path.exists(filename.encode(enc, 'replace')):
            logger.info('%s exists, trying an alternative name' % filename)
            filename = basename + '-' + str(i) + ext  + "EXISTS"  # ADDED
            i += 1
        return filename

**Comment by probus** [comment]
Thanks for help, but I didn't understand any of that.
I should have added that I don't care about subtitles, but unfortunately wget started producing larger, unplayable files a while back (I'm guessing because of #181 ), so that isn't a good workaround either.

**Comment by aajanki** [comment]
The `--resume` switch now skips re-downloading a file that has already been completely downloaded.

Resuming a *partially* downloaded file still doesn't work (yle-dl start re-downloading from the beginning). Fixing that would require much more work than I'm currently able to spend on this. The range header suggested above doesn't really help on HLS streams that consists of several small segments instead of a single file. This issue will likely remain open until somebody implements partial HLS download capability on ffmpeg.

**Comment by aajanki** [comment]
The new release 20192131 doesn't download duplicate copies (so no need to set --resume anymore) and shows the "Resume not supported" warning only when it detects a partially downloaded file.

Resuming HLS streams (that is, most streams on Areena nowadays) is still not supported. That is something that should be implemented in ffmpeg and not yle-dl, so I'm closing this issue.
