### ISSUE TITLE
error: unrecognized arguments: --subtitlesonly

### ISSUE THREAD

**Issue by hugovk** [aajanki/yle-dl#197]
`--subtitlesonly` was added in https://github.com/aajanki/yle-dl/issues/150 but now causes an error:

```console
$ yle-dl --subtitlesonly <URL>
usage: yle-dl [-h] [-V] [-c FILENAME] [-i FILENAME] [-o FILENAME]
              [--output-template TEMPLATE] [--pipe] [--destdir DIR]
              [--showurl | --showtitle | --showepisodepage | --showmetadata]
              [--vfat] [--resume] [--ratelimit BR] [--proxy URI]
              [--postprocess CMD] [--audiolang LANG] [--sublang LANG]
              [--hardsubs] [--latestepisode] [--maxbitrate RATE]
              [--resolution RES] [--duration S] [--preferformat F]
              [--backend BE] [--rtmpdump PATH] [--ffmpeg PATH]
              [--ffprobe PATH] [--adobehds CMD] [--wget PATH]
              [url]
yle-dl: error: unrecognized arguments: --subtitlesonly
```

What was the reason for removing it? Is there a way to download subtitles but not the huge media file?

Thanks!

**Comment by aajanki** [comment]
I removed the `--subtitlesonly` in version 20190203 because the subtitles are now embedded in the media file so it's not possible to download just the subtitles. Or rather, it would be possible to re-implement the subtitles-as-a-separate-file functionality in addition to the embedded subtitles but I don't have time to do that, sorry.

**Comment by hugovk** [comment]
OK, thanks, that sounds out of scope for this tool.
