### ISSUE TITLE
Downloading from yle areena broken?

### ISSUE THREAD

**Issue by N00BMmika** [aajanki/yle-dl#198]
Using version yle-dl==20190502 with raspberry pi and trying to download video from yle areena. If not giving output file name then I get error " No such file or directory" This may be bcause of my codepage is set incorrectly.

If giving filename with -o then I get just small binary file which contains some subtitles as ascii text.

Earlier I have been successfully run yle-dl in the system. Not sure if it went brokes after some update of my system or change in yle areena. Could you check if your yle-dl still work?

**Comment by N00BMmika** [comment]
--backend wget seems to work.

**Comment by aajanki** [comment]
Can you provide a debug log with `yle-dl --verbose ...` for an execution that end with "No such file or directory"?

The second issue of getting a small ascii text file is probably the same as #202. It can be fixed by either upgrading yle-dl to the latest version in git or by upgrading ffmpeg to 4.1 or later.

**Comment by N00BMmika** [comment]
Hi, the root cause of the problem was that I had some kind of issues with locale and putty and unicode chars in raspberry pi. When not using putty there is no issues.
