### ISSUE TITLE
Subtitles not being saved

### ISSUE THREAD

**Issue by zagrim** [aajanki/yle-dl#234]
It seems that currently no subtitles are being saved, although the debug output shows there are subtitle streams available. Tried first with latest episodes of https://areena.yle.fi/1-351677 and verified https://areena.yle.fi/1-50328288. It doesn't make a difference if `--sublang all` is specified or not.
Debug output: https://controlc.com/95577859
ffmpeg version: 4.1.4-1~deb10u1 (on Debian 10.3)

Thanks for this great project!

**Comment by aajanki** [comment]
Can you double-check with ffprobe that the file really doesn't contain subtitles: `ffprobe -i "file:Strömsö: Sipuleita keittiössä ja kasvimaalla-2020-02-29T00:01.mkv"`. It should show a subtitle stream similar to this if subtitles exist:
```
    Stream #0:0(fi): Subtitle: subrip (default)
    Metadata:
      VARIANT_BITRATE : 215497
      COMMENT         : käännöstekstitys
      ENCODER         : Lavc58.54.100 srt
      DURATION        : 00:28:09.099000000
```

The reason I'm asking to double check is because your debug log shows that the subtitles should have been downloaded:
```
Stream mapping:
  Stream #0:0 -> #0:0 (webvtt (native) -> subrip (srt))
  Stream #0:1 -> #0:1 (webvtt (native) -> subrip (srt))
```

Which video player are you using? On some players (at least VLC) subtitles might not always be displayed automatically, instead you need to select them from the menu.

**Comment by zagrim** [comment]
I'm sorry, the files seem to be fine, with subtitles included. I'm not quite sure if it was prior to upgrading yle-dl from 201910xx or why I didn't originally see any subtitles in VLC when I checked (from the Subtitles menu) and thus later on expected to see them as separate files like before. Totally my bad anyway. Everything's ok.
Having the subtitles together with the video in single file is way nicer than having separate files.

**Comment by skrinakron** [comment]
Note: As wget only downloads mp4 and the mp4 files don't contain subtitles (verified with ffprobe), this means that you no longer can get subtitles if you use wget as your downloader. My ffmpeg didn't support SSL/TLS and yle-dl therefore always fell back on wget, which meant no subtitles. The solution was to reinstall ffmpeg with https support to get at the mkv files.
