### ISSUE TITLE
[feature request] Archive file and writing metadata support

### ISSUE THREAD

**Issue by paju15** [aajanki/yle-dl#325]
It would be nice if yle-dl could support --archive and --add-metadata similar youtube-dl. 

Archive file support would help to download only new episodes even though older files are moved to final location from the download folder.

For metadata, it would be helpful if yle-dl could write program description e.g. to comment field for radio shows

**Comment by aajanki** [comment]
I agree that that kind of archival database would be useful, but I still won't be implementing it. I have decided to keep the focus of yle-dl only on the downloading because I don't have time to implement and maintain such an archival feature.

The missing metadata on radio shows is a bug. It's supposed to include the metadata automatically, but due to a bug yle-dl tries to attach the metadata to a video stream, and radio shows obviously don't have any video streams. I will fix that.

**Comment by aajanki** [comment]
Radio show metadata is now fixed on the master branch. The fix will be included in the next release.
