### ISSUE TITLE
an option to exclusively use lowercase characters in file and folder names

### ISSUE THREAD

**Issue by 07416** [aajanki/yle-dl#346]
[Similar to the feature (`--restrict-filename-no-spaces`) which replaces spaces](https://github.com/aajanki/yle-dl/issues/317). Since  in Unix-like OSes the filesystem is case-sensitive , many prefer avoiding uppercase characters in file and directory names.

You can presumably add another flag for this use case as well.

**Comment by aajanki** [comment]
You can do renaming with a postprocessing script: Create a shell script that gets the original file name as a parameter and renames the file to lower case letters. Then call yle-dl with the parameters `--postprocess your-script-here`. There is [an sample postprocessing script](https://github.com/aajanki/yle-dl/blob/master/scripts/muxmp4) (for converting the output to mp4) in the source codes.

I don't want to add another command line switch for this, because this sounds like an uncommon use case.
