### ISSUE TITLE
"No Streams Found"

### ISSUE THREAD

**Issue by DarrenPIngram** [aajanki/yle-dl#366]
```
 yle-dl "https://areena.yle.fi/1-4354262"
yle-dl 20240806: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2024 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

No streams found
```

Can it be some weirdness due to being clips (klipit)?

Other streams and programmes continue to be happy and unaffected, e.g. https://areena.yle.fi/1-50437783

**Comment by aajanki** [comment]
You guessed correctly that it's caused by the Klipit tab, or rather by the absence of the Jaksot tab. Usually Areena pages have both Jaksot and Klipit tabs. Yle-dl only detects episodes in the Jaksot tab, and now that it is missing, yle-dl finds nothing.

I'll see if I can change yle-dl to detect the selected tab instead of hard-coding the Jaksot tab.

**Comment by aajanki** [comment]
The master branch is now able to download streams from that page.
