### ISSUE TITLE
Canceling download sometimes corrupts the target file

### ISSUE THREAD

**Issue by hekkup** [aajanki/yle-dl#38]
Any way to recover a corrupted target file? Canceling the download corrupts the target file _sometimes_, after which it's not possible to resume the download.
For some reason qyledl or yle-downloader-gui corrupt the file with more certainty than yle-dl itself.
How to duplicate: use qyledl or yle-downloader-gui to download the file, but cancel the download and resume it. It may require a few cancels and restarts to cause corruption. After the file is corrupted, it's not possible to continue downloading it with yle-dl --resume.
Related: https://github.com/hekkup/qyledl/issues/1

**Comment by aajanki** [comment]
I believe that this is due to a bug in how rtmpdump handles resumes. [A patch](https://lists.mplayerhq.hu/pipermail/rtmpdump/2014-November/002399.html) was posted on the rtmpdump mailing list, but it is not yet included in the official repository. Also, [KSV's rtmpdump fork](http://stream-recorder.com/forum/customized-rtmpdump-binaries-patch-file-t16103.html) lists "Better resume support" as an improvement, which might fix the issue.

Anyway, I'm closing this bug report because this is a rtmpdump issue.
