### ISSUE TITLE
yle-dl "streaming" does not work 

### ISSUE THREAD

**Issue by ahjolinna** [aajanki/yle-dl#56]
yle-dl does not work with bomi/mpv/mplayer after 2.5.0 (arch pkgbuild, on chakraOS)
output:
http://pastebin.com/raw.php?i=RxNfmgFF

**Comment by aajanki** [comment]
Looks like yle-dl for some reason selects a wrong downloader backend for you. You can force the old behavior with --protocol switch as follows:

`yle-dl --protocol hds --pipe http://areena.yle.fi/tv/2409251 | mplayer -cache 1024 -`

**Comment by ahjolinna** [comment]
@aajanki : that didnt help, same errors

**Comment by aajanki** [comment]
Does the verbose log with -V reveal anything? Also, try to redirect stdout to a file and play the file afterwards.

`yle-dl -V --protocol hds --pipe http://areena.yle.fi/tv/2409251 > test.flv`

**Comment by ahjolinna** [comment]
@aajanki : -V output: http://pastebin.com/df6tfmra

**Comment by aajanki** [comment]
According to the log, the download completes without errors. Are you able to play test.flv in mplayer? What is the size of the file? When I run the above command, the resulting file was 44823222 bytes, and it plays fine in mplayer (MPlayer2 2.0-728-g2c378c7-4+b1).

**Comment by ahjolinna** [comment]
its just 64 bytes and I oc cant play it with mpv-git nor mplayer1(latest version, mplayer2 is dead so it was dropped from chakraOS repos). btw. what distro do u use?

**Comment by aajanki** [comment]
The log shows that yle-dl calls AdobeHDS.php correctly, so it looks like the problem is in AdobeHDS.php. Try to update it to the latest version. Delete /usr/local/share/yle-dl/AdobeHDS.php and run `make install-adobehds` in yle-dl directory again.

I changed yle-dl to run AdobeHDS.php in the debug mode when yle-dl is called with -V. You can get the latest yle-dl from git and rerun it with -V in case AdobeHDS.php shows something useful in the debug mode.

I'm using Debian unstable.

**Comment by ahjolinna** [comment]
btw. "Huulivoide" the yle-dl aur pkgbuild maintainer has removed from the 2.5.0 pkgbuild the line that would install AdobeHDS.php...(https://aur.archlinux.org/packages/yle-dl/), plz don't say that this is the problem

**Comment by ahjolinna** [comment]
now it works with the aur 2.5.1 pkgbuild
