### ISSUE TITLE
Failed to import youtube_dl

### ISSUE THREAD

**Issue by licensetokewl** [aajanki/yle-dl#64]
I have youtube-dl version 2015.05.15 installed. I'm guessing it's because python version thingy?

**Comment by aajanki** [comment]
Which distro are you using? Have you installed youtube-dl from your distro's repository or by using pip?

You need to have the youtube-dl module for Python 2. Some distros package only the Python 3 modules. If that is the case, follow the pip instructions on the [youtube-dl download page](https://rg3.github.io/youtube-dl/download.html), but use pip2 instead of pip.

**Comment by licensetokewl** [comment]
I'm using arch linux. I tried that pip2 thing and it works now! Thank you!
