### ISSUE TITLE
FLV file downloads, but cannot be read by VLC or ffmpeg

### ISSUE THREAD

**Issue by burke3gd** [aajanki/yle-dl#66]
I ran across this weird issue that only seems to concern the episodes of Hatfields & McCoys (so far):
http://areena.yle.fi/1-2156082
The FLV files are downloaded fine as usual, but they cannot be played back. Neither VLC or ffmpeg recognize them as video files.
Other programmes work fine (The Leftovers, Enlightened, etc).
Thanks for creating this great utility and hopefully the problem can be solved.

**Comment by aajanki** [comment]
Some streams are DRM-protected and cannot be played with any open source player (as far as I know).

If you update AdobeHDS.php to a recent version, it should recognize a DRM-protected stream and print out the following message: "This stream is encrypted with Akamai DRM. Decryption of such streams isn't currently possible with this script."

I'm closing this issue, because there is already an open issue #27 about the DRM-protection.
