### ISSUE TITLE
cookies with timestamp or similar

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#75]
if one runs two or more yle-dl in same directory first cookie gets overwritten.
Added timestamp (or random )
Also leaves clue if somethning went wrong when not deleted
//  $cc  = new cURL();
    $cc  = new cURL(true,strftime('Cookie-%Y-%m-%d-%H_%M_%S.txt'));

**Comment by aajanki** [comment]
Please suggest this to the maintainer of the AdobeHDS.php at https://github.com/K-S-V/Scripts.

The AdobeHDS.php in yle-dl is a direct copy of the file in K-S-V/Scripts and I would not like to introduce any divergences from the upstream file because otherwise syncing an updated version of the K-S-V script would get more complicated (I would need to apply patches everytime).
