### ISSUE TITLE
Can't download videos from swedish part of Yle

### ISSUE THREAD

**Issue by yleisalways** [aajanki/yle-dl#90]
I am having trouble downloading videos with yle-dl from svenska.yle.fi, where content from Yle is published in Swedish.

Example link:

https://svenska.yle.fi/artikel/2006/09/08/linus-torvalds-fran-universitetsnord-till-microsofts-utmanare

The error message I am getting:

Can't read http://player.yle.fi/api/v1/programs.jsonp?id=26-56568&callback=yleEmbed.programJsonpCallback: HTTP Error 404: Not Found
Unsupported stream: Failed to download program data

Is there any way to to make yle-dl download videos from svenska.yle.fi?

**Comment by aajanki** [comment]
The latest Github version improves the support for the svenska.yle.fi. Yle-dl seems to be able to download most clips now.

There most likely are some clips that do not work, because Yle Arkivet has half a dozen different ways of embedding a video on the page, and yle-dl only supports the most common one. Open a new bug report with a link to a webpage if you come across any non-downloadable clips.
