### ISSUE TITLE
Link to "Gentoo ebuild" doesnt work

### ISSUE THREAD

**Issue by juippis** [aajanki/yle-dl#93]
Hey, 

in your homepage 
http://aajanki.github.io/yle-dl/index-en.html
the link to "Gentoo ebuild" doesnt work anymore. Ive kept yle-dl up-to-date in my local repository, but decided to join Github now. Its available here, 
https://github.com/juippis/jps-gentoo/tree/master/media-video/yle-dl

**Comment by harski** [comment]
I have also been maintaining a repository containing an up-to-date version of yle-dl: https://github.com/harski/pakki/tree/master/media-video/yle-dl

@juippis good thinking adding that ewarn if php USE flag is not set. I used to have a patch that removed adobeHDS support completely from the script if -adobehds was set, but sadly it broke with last July's refactor commits (starting with fa35ccf06c2730a0da737cac300330727be2e84a). After that I simply made adobeHDS mandatory.

Otherwise my ebuild looks a bit more finished, take a look and feel free to copy the relevant parts to your ebuild.

**Comment by juippis** [comment]
Kah, moro Tuomo :)

-----
Yeah, I should refine the ebuild when a newer version of yle-dl is released. AdobeHDS shouldnt be installed at all if its not chosen by the user. If I recall correctly, yle-dl used to use youtube-dl as a default backend if AdobeHDS wasnt found / didnt work, without appending the --backend option. Im sure its still doable with a line of sed (or two), but need to look into it later.

**Comment by aajanki** [comment]
I added links to both of your repos. Thanks!
